---
title:"Team Analysis"
author: Hayden Tinker
start date: April 14,2022
output:
  pdf_document:
    number_section:false
---

## Step 1 Collect Data
  Oracles Elixir has made their match data for the 2022 season public and that is where I will be pulling my data from. Here is a link to download the data: https://oracleselixir.com/tools/downloads
  
## Step 2 Exploration and Preparing the Data
```{r}
#Create df from the csv
matchData <- read.csv("2022_Match_Data_AllRegions.csv",stringsAsFactors=TRUE)
matchData_df<-as.data.frame(matchData)
```

```{r}
#Look at which cols to get rid of. I chose to get rid of the ones that have nothing to do with the game.
teamsData_df<-matchData_df[(matchData_df$position=="team"),]
columns<- colnames(teamsData_df)
columns
teamsData_df<-matchData_df[,-c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24)]

#Taking care of NA
teamsData_df[is.na(teamsData_df)] <- 0
```

#Model 1
```{r}
library(nnet)
#Sample data
train_sample<-sample(57252,57252*0.75)
#Divide into training and testing
game.train<-teamsData_df[train_sample,]
game.test<-teamsData_df[-train_sample,]
#Create model
game.model<-nnet(result~.,data=game.train,size=2)
#Get results
game.results<-predict(game.model,game.test[-game.test$result])

```
#Model 1 Results
```{r}
#Round the results to compare to actual match results
for(i in 1:length(game.results)){
  if(game.results[i]<.5){
    game.results[i]<-0
  }else{
    game.results[i]<-1
  }
}
#Get cor, create a table, and get percentage correct
cor(game.results,game.test$result)
table(game.results,game.test$result)
predResults<-game.results==game.test$result
predPercent<-sum(predResults)/length(game.results)
predPercent
```

#Model 2
```{r}
#Get a sample on the data
train_sample2<-sample(57252,57252*0.75)
#Divide into test and training sets
game.train2<-teamsData_df[train_sample,]
game.test2<-teamsData_df[-train_sample,]
#Create Model
game.model2<-nnet(result~.,data=game.train2,size=5)
#Get Predictions for test
game.results2<-predict(game.model2,game.test2[-game.test2$result])

```
#Model 2 Results
```{r}
#Essentially rounding the results so I can compare to actual results of match
for(i in 1:length(game.results2)){
  if(game.results2[i]<.5){
    game.results2[i]<-0
  }else{
    game.results2[i]<-1
  }
}
#Get cor 
cor(game.results2,game.test2$result)
#Make a table with the results
table(game.results2,game.test2$result)
#Get a percentage of correct results
predResults2<-game.results2==game.test2$result
predPercent2<-sum(predResults2)/length(game.results2)
predPercent2

```