---
title:"Team Analysis"
author: Hayden Tinker
start date: April 14,2022
output:
  pdf_document:
    number_section:false
---

## Step 1 Collect Data
  Oracles Elixir has made their match data for the 2022 season public and that is where I will be pulling my data from. Here is a link to download the data: https://oracleselixir.com/tools/downloads
  
## Step 2 Exploration and Preparing the Data
```{r}
#Create df from the csv
matchData <- read.csv("matchData/2022_Match_Data_AllRegions.csv",stringsAsFactors=TRUE)
matchData_df<-as.data.frame(matchData)
```

```{r}
#Look at which cols to get rid of. I chose to get rid of the ones that have nothing to do with the game.
teamsData_df<-matchData_df[(matchData_df$position=="team"),]
columns<- colnames(teamsData_df)
columns
teamsData_df<-matchData_df[,-c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24)]

#For now I will be setting the NA to 0. Every row of the data contains at least 1 NA. I will take care of the NA later on when I try to improve the model,.
teamsData_df[is.na(teamsData_df)] <- 0
```



#Model 1
```{r}

#linear regression model
games.model_lm<-lm(formula=result ~.,teamsData_df)
summary(games.model_lm)
teamsData_df$pred<-predict(games.model_lm,teamsData_df)


```

#Model 1 Results
```{r}
#Round the results to compare to actual match results
for(i in 1:length(teamsData_df$pred)){
  if(teamsData_df$pred[i]<.5){
    teamsData_df$pred[i]<-0
  }else{
    teamsData_df$pred[i]<-1
  }
}
#Get the cor and plot the results
cor(teamsData_df$pred,teamsData_df$result)
plot(teamsData_df$pred,teamsData_df$result)
```


```{r}
#Make a pred for a team of your choice
team1<-matchData_df[matchData_df$teamname=="G2 Esports",]
team1<-team1[,-c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24)]
team1[is.na(team1)] <- 0
team1Mean_df<-as.data.frame(rbind(colMeans(team1)))
team1Mean_df$pred<-0
team1Mean_df$pred<-predict(games.model_lm,team1Mean_df)
team1Mean_df$pred

```